version: 2.0.0.{build}

environment:
  releaseVersion: 2.0.0
  packageVersion: 2.0.0-pre4

assembly_info:
  patch: true
  file: VersionInfo.cs
  assembly_version: "$(releaseVersion)"
  assembly_file_version: "{version}"
  assembly_informational_version: "$(packageVersion)"

nuget:
  account_feed: true

platform: Any CPU

configuration: Release

before_build:
  - nuget restore

build:
  project: CodeOnlyStoredProcedure.sln

test:
  assemblies:
    - CodeOnlyTests.dll
    - CodeOnlyTests-NET40.dll

# run smoke tests, and create the nuget package artifacts
after_test:
  - .\SmokeTests\bin\Release\SmokeTests.exe
  - .\SmokeTests-NET40\bin\Release\SmokeTests-NET40.exe
  - ps: nuget pack CodeOnlyStoredProcedures.nuspec -Symbols -NonInteractive -Verbosity detailed -Exclude "**\Contracts\*" -Version $env:packageVersion
  - ps: nuget pack CodeOnlyStoredProcedures.nuspec -NonInteractive -Verbosity detailed -Exclude "**\*.cs;**\*.pdb" -Version $env:packageVersion

artifacts:
  - path: '*.nupkg'

deploy:
  - provider: NuGet
    on:
      branch: master
    api_key:
      secure: YpmJQ9N6F0dfai0xFAoerzB7nruq9NOlhDquhAliwy5cS2A87wU7U+X4Q5eH8vyx
    skip_symbols: false
    artifact: /.*\.nupkg/