version: 2.0.0.{build}

environment:
  releaseVersion: 2.0.0
  packageVersion: 2.0.0-pre2

assembly_info:
  patch: true
  file: VersionInfo.cs
  assembly_version: "$(releaseVersion)"
  assembly_file_version: "{version}"
  assembly_informational_version: "$(packageVersion)"

nuget:
  account_feed: true

platform: Any CPU

configuration: Release

before_build:
  - nuget restore

build:
  project: CodeOnlyStoredProcedure.sln

test:
  assemblies:
    - CodeOnlyTests.dll
    - CodeOnlyTests-NET40.dll

# run smoke tests, and create the nuget package artifacts
after_test:
  - .\SmokeTests\bin\Release\SmokeTests.exe
  - .\SmokeTests-NET40\bin\Release\SmokeTests-NET40.exe
  - nuget pack CodeOnlyStoredProcedures.nuspec -Symbols -NonInteractive -Verbosity detailed

artifacts:
  - path: '*.nupkg'

#deploy:
#  - provider: NuGet
#    server: 
#      secure: KWCy/cmXPCGCHxgZeYVi0Z5eq7MZCUDzY9oqGs9kpMPNvbAYfK5s0aOS8JwzEOlb699R302QO80G2DiLB7Naow==
#    api_key:
#      secure: BpvfN0VAXhEcYOXAk1rq6OFRg85yKBz4Zc+GMXhdvb8=
#    skip_symbols: true
#    artifact: /.*\.nupkg/